#服务端口
server:
  port: 8089
#数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Wzh20031015
    url: jdbc:mysql://localhost:3306/strore?character=utf-8&serverTimezone=UTC
  redis:   #redis配置
    host: 127.0.0.1
    port: 6379
    password: Wzh20031015
mybatis: #整合mybatis配置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.zxst.shoop.entity

alinfo:
  oss-endpoint: oss-cn-qingdao.aliyuncs.com
  oss-accesskeyid: LTAI5tEJ53Gsf7wkoN6toZpn
  oss-accesskeysecret: Cc5GzpLxKJlave4uQqFR7YwSuD3dHD
  oss-bucketname: zxst-shoop-wzh
#每个用户最多10个地址
user:
  address:
    max-count: 10